### ISSUE TITLE
types-registry stopped publishing?

### ISSUE THREAD

**Issue by moltar** [microsoft/DefinitelyTyped-tools#1056]
Last release was 4 months ago?

https://www.npmjs.com/package/types-registry?activeTab=versions

**Comment by jakebailey** [comment]
Yeah, failing: https://github.com/microsoft/DefinitelyTyped-tools/actions/workflows/publish-registry.yml

**Comment by jakebailey** [comment]
0.1.686 was just published successfully. Thanks for telling us; need to add some badges to the readme or something...
