### ISSUE TITLE
@types/eslint module not found by bot

### ISSUE THREAD

**Issue by cbejensen** [microsoft/DefinitelyTyped-tools#1107]
See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71207#discussioncomment-11310850

![Image](https://github.com/user-attachments/assets/2393516a-0b89-4c22-a0ec-14611dc32ce4)

**Comment by jakebailey** [comment]
The package doesn't exist on DT anymore https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/eslint

We'd have to restore the package to address your issue

**Comment by jakebailey** [comment]
Closing as working-as-intended, but commented at the other thread.
