### ISSUE TITLE
Can you expose an interface for type query?

### ISSUE THREAD

**Issue by zytjs** [microsoft/DefinitelyTyped-tools#113]
I am developing an npm package, which can install type packages automatically when user exec `npm install xxx` or `yarn add xxx`, but now i suffers from no good type query interface.

I kown the search-json https://typespublisher.blob.core.windows.net/typespublisher/data/search-index-min.json , but its size is very large, requesting it will be very slow. And i notice the query page migrates from https://microsoft.github.io/TypeSearch/?search= to https://www.typescriptlang.org/dt/search?search= which use Algolia.

So is there an interface for those in need like me to query?

Sorry for my poor En.

**Comment by orta** [comment]
We now use the algolia npm index, https://www.typescriptlang.org/dt/search - I'd reach out to Haroenv on twitter/github about whether you can get access

**Comment by zytjs** [comment]
> We now use the algolia npm index, https://www.typescriptlang.org/dt/search - I'd reach out to Haroenv on twitter/github about whether you can get access

Thanks a lot

**Comment by zytjs** [comment]
Hi, is there any news now

**Comment by andrewbranch** [comment]
> I'd reach out to Haroenv on twitter/github about whether you can get access

@zytjs sorry for the delay; I think there was a miscommunication here—@orta was suggesting that _you_ should reach out to Haroenv and ask for what you’re looking for. At any rate, I don’t think this issue is related to this repo, so I’m going to close. Good luck developing your installer tool!
