### ISSUE TITLE
DTSLint fails to find config for dependents

### ISSUE THREAD

**Issue by BoruiGu** [microsoft/DefinitelyTyped-tools#362]
`npm run test-all` in DefinitelyTyped package is failing when the changed package has dependents

for example
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57500
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57501
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57502

the error is
```
Could not find config file at: .../DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/dtslint.json
```

i debugged this and think the issue is with this line
https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/src/lint.ts#L38

the lint.js is located in `dtslint/bin/src/lint.js`, but the `dtslint-expect-only.json` is in `dtslint` (outside of the bin)

thus `path.join(__dirname, "..", "dtslint-expect-only.json")` could not find the `dtslint-expect-only.json`

**Comment by sandersn** [comment]
Ah, I it needs another `..`, because the location of `lint.js` changed from `bin/lint.js` to `bin/src/lint.js`

**Comment by sandersn** [comment]
Will be fixed by https://github.com/microsoft/DefinitelyTyped-tools/pull/363

**Comment by BoruiGu** [comment]
thanks @sandersn! do you know how to rerun the CI checks on these PRs?

**Comment by sandersn** [comment]
I always close/re-open the PRs.
I'm waiting for the new packages to publish first, however.

**Comment by sandersn** [comment]
I restarted the first PR on the list and tests now pass.
