### ISSUE TITLE
URLs still point to the wrong place

### ISSUE THREAD

**Issue by wbt** [microsoft/DefinitelyTyped-tools#400]
When preparing a contribution for DefinitelyTyped, one should run `npm test <pkg>` which runs 
> definitely-typed@0.0.3 test
> dtslint types "\<pkg\>"

Errors printed by linting rules still point into the https://github.com/Microsoft/dtslint/blob/master/docs/ \<rule\> path but the main readme says the repo has moved here. The URLs should be updated too.

**Comment by jablko** [comment]
@wbt This is fixed now, in https://github.com/microsoft/DefinitelyTyped-tools/pull/441, I think?
