### ISSUE TITLE
Failure on parallel npm module install when running against `node` typings

### ISSUE THREAD

**Issue by SimonSchick** [microsoft/DefinitelyTyped-tools#41]
See build https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=24313
I've ran into the same issue on MacOS so this is not isolated and occurs *very* frequently.

I was able to to reduce the frequency *drastically* by reducing the parallelism in https://github.com/microsoft/types-publisher/blob/e3ccf31258ae76af4dffbbe44297af2c435f7dd7/src/tester/test-runner.ts#L144

eg. `Math.floor(nProcesses / 4)`.

This didn't really affect testing speed.

I realise this is an npm issue but maybe some steps should be taken to ensure smooth sailing for us in the meantime.

Suggested solutions: 
- Reduce parallelism, should probably restrict to 4 threads max.
- Add retry to handle this specific error.

**Comment by jakebailey** [comment]
The tooling no longer installs dependencies; pnpm is used to manage all of that.
