### ISSUE TITLE
Dependency detected but not installed

### ISSUE THREAD

**Issue by eps1lon** [microsoft/DefinitelyTyped-tools#422]
Example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59519 (failing in https://github.com/DefinitelyTyped/DefinitelyTyped/runs/5726980310?check_suite_focus=true)

`styled-components` was correctly identified to depend on `react-native`. However, dependencies of `styled-components` weren't installed so tests are failing.

**Comment by eps1lon** [comment]
Also blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59691

**Comment by reichhartd** [comment]
Duplicate of https://github.com/microsoft/DefinitelyTyped-tools/issues/413
