### ISSUE TITLE
`@latest` tag on npm does not point to the "latest" version

### ISSUE THREAD

**Issue by eps1lon** [microsoft/DefinitelyTyped-tools#443]
https://www.npmjs.com/package/@types/react-dom contains [18.0.2](https://www.npmjs.com/package/@types/react-dom/v/18.0.2) but the `latest` distribution tag still points to 18.0.0 even though 18.0.2 was published after 18.0.0.
![Screenshot from 2022-04-28 20-38-10](https://user-images.githubusercontent.com/12292047/165823386-b003ef17-b3aa-446b-b820-9191870abd12.png)

```bash
$ npm dist-tag @types/react-dom
latest: 18.0.0
ts2.0: 0.14.20
ts2.1: 15.5.0
ts2.2: 15.5.0
ts2.3: 16.0.3
ts2.4: 16.0.3
ts2.5: 16.0.3
ts2.6: 16.0.6
ts2.7: 16.0.6
ts2.8: 16.9.7
ts2.9: 16.9.8
ts3.0: 16.9.8
ts3.1: 16.9.8
ts3.2: 16.9.9
ts3.3: 17.0.0
ts3.4: 17.0.1
ts3.5: 17.0.5
ts3.6: 17.0.9
ts3.7: 17.0.11
ts3.8: 17.0.11
ts3.9: 18.0.2
ts4.0: 18.0.2
ts4.1: 18.0.2
ts4.2: 18.0.2
ts4.3: 18.0.2
ts4.4: 18.0.2
ts4.5: 18.0.2
ts4.6: 18.0.2
ts4.7: 18.0.2
```

Original report: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59748#issuecomment-1112463904

**Comment by weswigham** [comment]
@sandersn and I briefly looked at the logs - it looks like publishing an old version (v15) after 18.0.1 moved the `latest` tag back to `18.0.0` and not `18.0.1` and from there messed up everything - now every time we try to publish the latest tag we're confused why it's not a patch bump and error.
