### ISSUE TITLE
Is there a plan for us?

### ISSUE THREAD

**Issue by taoqf** [microsoft/DefinitelyTyped-tools#46]
I could not install dependencies, because of gfw, we chinese could not access `raw.githubusercontent.com` now.

```sh
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://raw.githubusercontent.com/Microsoft/types-publisher/fc21ead08a786201e1874c1f4b61308f1bbdbdf2/package.json: connect ECONNREFUSED 151.101.228.133:443".
```

**Comment by sandersn** [comment]
Can you give more detail on this? It's possible (but not likely) that the move to microsoft/DefinitelyTyped-tools fixed this. Did it?

**Comment by orta** [comment]
This should be fixed now (it resolves via npm)!
