### ISSUE TITLE
Bug: Files that are only referenced using `typeof import(…)` must be added to `OTHER_FILES.txt`

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/DefinitelyTyped-tools#47]
See <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44805> (specifically <https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/688383681>).

The expected behaviour is that <https://github.com/DefinitelyTyped/DefinitelyTyped/commit/06eb285a3042aabe88c28961cdddff1b83fdf15f> is not needed when those files are referenced only using `typeof import(…)`.

**Comment by sandersn** [comment]
Similar to #44
