### ISSUE TITLE
[dtslint] Possible to opt out of ts-ignore flagging?

### ISSUE THREAD

**Issue by thw0rted** [microsoft/DefinitelyTyped-tools#511]
I know [everybody thinks they have a good reason](https://github.com/microsoft/TypeScript/issues/19573) why they *really* need ts-ignore, but, please hear me out.

I would like to help [fix some types for an isomorphic library](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52064).  I've been looking for a non-terrible way to do this for [quite some time](https://stackoverflow.com/questions/65848540/right-way-to-reference-platform-specific-types-in-isomorphic-typescript-library).  There are several proposals out there to address the problem (e.g. https://github.com/microsoft/TypeScript/issues/31894 and https://github.com/microsoft/TypeScript/issues/3538) but unfortunately none have actually been implemented.

In the interim, I'm pretty sure I have found [an ugly, dirty hack of a workaround](https://github.com/microsoft/TypeScript/issues/31894#issuecomment-977901178) that I'm pretty sure completely solves the problem with no side effects.  Unfortunately, it requires tactical use of `@ts-ignore`:

```ts
// @ts-ignore
type NodeReadableStream = any extends NodeJS.ReadableStream ? never: NodeJS.ReadableStream;
```

If the consuming project includes `@types/node`, the above will be an alias to `ReadableStream`.  If they do not, it will be `never` (and thus cleanly erase out of type unions).  Without `@ts-ignore`, though, it will break the build and require consumers to use `skipLibChecks`.

I started to use the above workaround in a type package update but the tests failed with `'ts-ignore' is forbidden`.  I only found [one previous issue discussing this error](https://github.com/microsoft/dtslint/issues/297), but it was about an ignore-comment in a dependency.  Is there a way to intentionally introduce a `ts-ignore` into a types package?  If not, can we get one?  (If not, does anybody have a better workaround for the problem than mine?)

**Comment by thw0rted** [comment]
A commenter in another thread posted code with `// eslint-disable-next-line @typescript-eslint/ban-ts-comment`, but I assume dts-lint does not respect that out of the box.  It could provide an example syntax for implementation, at least.

**Comment by jakebailey** [comment]
This is now possible as of #700, though you definitely should not use this if a better option is available, which should be true basically always.
