### ISSUE TITLE
Allow using mask/pattern in allowedPackageJsonDependencies.txt

### ISSUE THREAD

**Issue by Maxim-Mazurok** [microsoft/DefinitelyTyped-tools#542]
Once in a while, I sync all newly added and removed Google API type definitions.
This is a process that requires many steps:
1. Add new APIs in this repo
2. Remove old APIs from DT
3. Remove old APIs from this repo

Because all these PRs take time to get merged, this can be dragged for days or weeks.
Examples of such PRs I opened to this repo: #541 (thanks for a prompt merge!), #499, #469, #463, #315, #311, #263, #240, #183, #175, #174, #156.

It would be a huge relief for me (and DT maintainers) if I didn't have to update `allowedPackageJsonDependencies.txt` here all the time.
All of the packages follow the same pattern/mask: `@maxim_mazurok/gapi.client.*`.
Furthermore, since they all are prefixed with `@maxim_mazurok/` so only I can publish packages matching this pattern.
I also have 2FA set up and secured by both my GitHub and Twitter accounts as well:
![screenshot npm settings](https://user-images.githubusercontent.com/7756211/192657195-ef6bf075-301c-40c0-ba5e-c7c7324f7fab.png)

I would like to automate this process, but this likely will increase the frequency of the PRs and add unnecessary workload for DT maintainers. It can potentially be reduced by only creating PRs once a month, for example. But that would mean that users of the new APIs will have to wait for a month before they can use them with TS which isn't ideal.

Alternatively, if we allow using patterns in package names when the owner prefix is present - it'll be safe enough while providing quality of life improvements for those who need it.

Please let me know your thoughts on this, cheers!

**Comment by Maxim-Mazurok** [comment]
Any update on this would be appreciated ☺️

**Comment by jakebailey** [comment]
I think based on talking to @sandersn and @andrewbranch that we want to keep this list still as a straight list.

What aspect of this process are you trying to automate? PRs to this repo? PRs to DT itself? Which one are you seeing move too slowly? I am subscribed to everything on this repo and like to empty my inbox, so it seems unlikely that something will sit for too long if it's non-controversial.

(Of course, the ultimate best is to just have people set `"types"` or use `references`, then none of this would be needed at all... 5% of DT is just `gapi.*`)

**Comment by Maxim-Mazurok** [comment]
> What aspect of this process are you trying to automate? PRs to this repo? PRs to DT itself? Which one are you seeing move too slowly?
I'd like to automate both. In my recent experience, it was quite quick. However keep in mind that now it's a manual process and I only do this when I feel like it, maybe once every few months. Automation may result in daily PRs, depending on how often Google releases new versions of its APIs, and they have a lot of them. Perhaps I could throttle it down to like once a month, that might be an acceptable balance. What do you think?

> the ultimate best is to just have people set `"types"` or use `references`, then none of this would be needed at all...

Do you mean asking my users to add something like this to their tsconfig files?
```json
{
  "compilerOptions": {
    "types": ["@maxim_mazurok/gapi.client.sheets-v4"]
  }
}
```

This is an interesting option... However, I'm quite concerned about how this will affect project discovery. I'd imagine most developers looking in DT for available types. I don't think I've ever used any types that were published separately. I usually consume either shipped types with code, `@types/*` packages or write them myself.

Perhaps, if it was possible to reference these in Google's API documentation and samples - then the need for discovery wouldn't be so strong. I haven't looked into that option yet TBH.

**Comment by jakebailey** [comment]
Yes, that's correct; one can do anything `@types` can without DT by explicitly listing out more packages to load. The only benefit of DT is that TS's (unfortunate) default is to load _everything_ in `@types` automatically.

>  However, I'm quite concerned about how this will affect project discovery. I'd imagine most developers looking in DT for available types.

What do you mean by "looking in DT"? I don't think anyone's actually going to the DT repo to look for things; the repo is far too large to navigate in GitHub. Searching for types packages, maybe, but if you're already on npm, that's just a normal search and looking for the package will find all of them. See: https://www.npmjs.com/search?q=gapi.client.sheets

**Comment by Maxim-Mazurok** [comment]
> What do you mean by "looking in DT"?

I guess I meant the `@types/*` "brand". But I see your point, perhaps it's reasonable moving forward, especially if I can get someone from Google to mention usage of my types in the official docs.
