### ISSUE TITLE
Port custom tslint rules to eslint

### ISSUE THREAD

**Issue by sandersn** [microsoft/DefinitelyTyped-tools#648]
This is a tracking issue to co-ordinate work:

Done:

- no-outside-dependencies #650 
- no-import-default-of-export-equals
- no-self-import
- no-single-element-tuple-type
- no-relative-import-in-test
- no-redundant-jsdoc2 (though the new name should be no-redundant-jsdoc unless there's a built-in eslint rule already)

In-progress:

- no-single-declare-module

Not started:

- no-padding
- strict-export-declare-modifier
- npm-naming
- expect

Comment on this issue to let me know that you're working on a rule and I'll avoid working on it myself.

*Also* dtslint uses lots of default tslint rules. These all need eslint equivalents. I hope most (all?) of them are already written, but they all need to be tested and added to DT's .eslintrc.json.

**Comment by JoshuaKGoldberg** [comment]
no-self-import looks quick, tackling it now...

**Comment by JoshuaKGoldberg** [comment]
no-single-element-tuple-type too...

**Comment by jakebailey** [comment]
If we're going to use `eslint-plugin-jsdoc`, we will definitely need to verify that it doesn't negatively impact performance. I removed this plugin from the TS repo for that reason; its parsing of JSDoc was extremely inefficient.

**Comment by JoshuaKGoldberg** [comment]
> verify that it doesn't negatively impact performance

...indeed. In the `DefinitelyTyped` repo, after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65445:

<table>
<thead>
<tr>
<th>Variant</th>
<th>Timing</th>
</tr>
</thead>
<tbody>
<tr>
<td>Baseline</td>
<td><code>8.621 s ±  0.249 s</code></td>
</tr>
<tr>
<td><code>jsdoc</code></td>
<td><code>17.843 s ±  0.656 s</code></td>
</tr>
</tbody>
</table>

<details>
<summary>Getting performance measurements locally</summary>

After installing [`eslint-plugin-local-rules`](https://github.com/cletusw/eslint-plugin-local-rules):

```shell
npm i -D eslint-plugin-local-rules
```

I made the following two files:

<details>
<summary><code>.eslint-local-rules.cjs</code></summary>

```js
const dtHeader = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/dt-header");
const exportJustNamespace = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/export-just-namespace");
const noAnyUnion = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-any-union");
const noBadReference = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-bad-reference");
const noConstEnum = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-const-enum");
const noDeadReference = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-dead-reference");
const noSingleElementTupleType = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-single-element-tuple-type");
const noUselessFiles = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/no-useless-files");
const preferDeclareFunction = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/prefer-declare-function");
const redundantUndefined = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/redundant-undefined");
const trimFile = require("../DefinitelyTyped-tools/packages/dtslint/dist/rules/trim-file");

module.exports = {
  "dt-header": dtHeader,
  "export-just-namespace": exportJustNamespace,
  "no-any-union": noAnyUnion,
  "no-bad-reference": noBadReference,
  "no-const-enum": noConstEnum,
  "no-dead-reference": noDeadReference,
  "no-single-element-tuple-type": noSingleElementTupleType,
  "no-useless-files": noUselessFiles,
  "prefer-declare-function": preferDeclareFunction,
  "redundant-undefined": redundantUndefined,
  "trim-file": trimFile,
};
```

</details>

<details>
<summary><code>.eslintrc.json</code></summary>

```json
{
  "root": true,
  "extends": [],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "warnOnUnsupportedTypeScriptVersion": false
  },
  "plugins": ["@typescript-eslint", "jsdoc", "local-rules"],
  "rules": {
    "jsdoc/check-tag-names": [
      "error",
      {
        "definedTags": [
          "addVersion",
          "api",
          "author",
          "beta",
          "brief",
          "category",
          "cfg",
          "chainable",
          "check",
          "classDescription",
          "condparamprivilege",
          "constraint",
          "credits",
          "declaration",
          "defApiFeature",
          "defaultValue",
          "detail",
          "end",
          "eventproperty",
          "experimental",
          "export",
          "expose",
          "extendscript",
          "factory",
          "field",
          "final",
          "fixme",
          "fluent",
          "for",
          "governance",
          "header",
          "hidden-property",
          "hidden",
          "id",
          "label",
          "language",
          "link",
          "listen",
          "locus",
          "methodOf",
          "minVersion",
          "ngdoc",
          "nonstandard",
          "note",
          "npm",
          "observable",
          "option",
          "optionobject",
          "options",
          "packageDocumentation",
          "param",
          "parent",
          "platform",
          "plugin",
          "preserve",
          "privateRemarks",
          "privilegeLevel",
          "privilegeName",
          "proposed",
          "range",
          "readOnly",
          "related",
          "remark",
          "remarks",
          "required",
          "requires",
          "restriction",
          "returnType",
          "section",
          "see",
          "since",
          "const",
          "singleton",
          "source",
          "struct",
          "suppress",
          "targetfolder",
          "enum",
          "title",
          "record",
          "title",
          "TODO",
          "trigger",
          "triggers",
          "typeparam",
          "typeParam",
          "unsupported",
          "url",
          "usage",
          "warn",
          "warning",
          "version"
        ],
        "typed": true
      }
    ],
    "local-rules/dt-header": "error",
    "local-rules/export-just-namespace": "error",
    "local-rules/no-any-union": "error",
    "local-rules/no-bad-reference": "error",
    "local-rules/no-const-enum": "error",
    "local-rules/no-dead-reference": "error",
    "local-rules/no-single-element-tuple-type": "error",
    "local-rules/no-useless-files": "error",
    "local-rules/prefer-declare-function": "error",
    "local-rules/redundant-undefined": "error",
    "local-rules/trim-file": "error"
  },
  "settings": {
    "jsdoc": {
      "tagNamePreference": {
        "argument": "argument",
        "exception": "exception",
        "function": "function",
        "method": "method",
        "param": "param",
        "return": "return",
        "returns": "returns"
      }
    }
  }
}
```

</details>

Then I ran `time npx eslint "types/a*/**/*.d.ts"` with and without the `jsdoc/check-tag-names` entry.

</details>

I'll take a look at `eslint-plugin-jsdoc` performance when I have time. cc @brettz & @gajus - I haven't checked how much of this is parsing vs. rule logic vs. other factors. If you have any advice/input that'd be lovely!

**Comment by jakebailey** [comment]
Yeah. It's basically loads of splitting by lines and other such stuff, compared to TS's parser.

**Comment by JoshuaKGoldberg** [comment]
The following DefinitelyTyped TSLint rules have rough ESLint equivalents in the wild:

* `expect`: [`@expect-type/expect`](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type)
* `padding`: [`padding-line-between-statements](https://eslint.org/docs/latest/rules/padding-line-between-statements`)
* `void-return`: [`@typescript-eslint/no-invalid-void-type`](https://typescript-eslint.io/rules/no-invalid-void-type)

...which leaves the following DefinitelyTyped TSLint rules:

* `no-import-default-of-export-equals`
* `no-relative-import-in-test`: #654
* `no-single-declare-module`: #655
* `npm-naming`
* `strict-export-declare-modifiers`

...we're pretty close! 😄

**Comment by JoshuaKGoldberg** [comment]
Ah, and good news on the performance! https://github.com/eslint/eslint/pull/17066 significantly improved the performance of ESLint's `utils.search`, which is frequently used for JSDoc parsing by `eslint-plugin-jsdoc` via a `getJSDocComment` function.

Running on a Macbook Air M2 with `eslint@8.38.0` (before the fix landed):

```plaintext
$ hyperfine "npx eslint \"types/a*/**/*.d.ts\"" --ignore-failure
Benchmark 1: npx eslint "types/a*/**/*.d.ts"
  Time (mean ± σ):     14.468 s ±  0.165 s    [User: 19.037 s, System: 1.023 s]
  Range (min … max):   14.060 s … 14.656 s    10 runs
```

Running on a Macbook Air M2 with `eslint@8.39.0` (which includes the fix):

```plaintext
$ hyperfine "npx eslint \"types/a*/**/*.d.ts\"" --ignore-failure
Benchmark 1: npx eslint "types/a*/**/*.d.ts"
  Time (mean ± σ):      8.057 s ±  0.237 s    [User: 12.593 s, System: 0.955 s]
  Range (min … max):    7.709 s …  8.530 s    10 runs
```

Nicely done @fasttime! 👏

**Comment by mastrzyz** [comment]
Going to take a look into porting `expect` to the ESLint rule @JoshuaKGoldberg  reccomended
