### ISSUE TITLE
Don’t use ESLint rulePaths

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/DefinitelyTyped-tools#691]
Currently `dtslint` uses the ESLint option `rulePaths`. This registers rules that can only be found by this particular instance of ESLint. In other words: It does not integrate with how one would normally run ESLint, e.g. by using `eslint .` or in an editor.

The solution would be to make these custom rules part of a plugin.

Refs https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61764

**Comment by jakebailey** [comment]
This is something I've wanted to try and do for a while (but never had the time to do). There's one outstanding question, though; if the rules are a plugin, how can we run it against multiple versions of TS?

Theoretically, there could be a plugin for use in the editor that just uses the version of TS in the workspace, then dtslint turns that off or something before running its normal stuff, maybe.

**Comment by remcohaszing** [comment]
I was not aware these rules require type information.

I would argue it’s even sufficient to verify this only against the latest stable TypeScript version in CI. It’s important to make sure the types work against all TypeScript versions, but is it really relevant that lint rules do?

**Comment by jakebailey** [comment]
I'm probably overthinking it; I'm not totally sure if all of the type-aware stuff is fully external to eslint/tslint or not. If it is... then my point is silly and yeah, a plugin would work a lot better.

**Comment by jakebailey** [comment]
But, I distinctively recall @sandersn having to futz around with clearing ts-eslint's `Program` cache and such to prevent OOMs, which would lead me to believe that we are in fact using something there. But if so, then we would have to be able to redirect uses of ts, so, basically I should be quiet now 😄

**Comment by sandersn** [comment]
A lot of my futzing was guided by @bradzacher. The weirdest lines of code are

```ts
  const estree = await import(require.resolve("@typescript-eslint/typescript-estree", { paths: [dirPath] }));
  process.env.TSESTREE_SINGLE_RUN = "true";
```

followed by a matching `estree.clearCaches()` after the usual `eslint.lintFiles` call in dtslint. As far as I recall, Brad told me that this was needed to get the version of typescript-eslint installed by DefinitelyTyped, not the one from DefinitelyTyped-tools. However, this may only apply to full, overnight runs, which download a copy of DefinitelyTyped alongside a clone of DefinitelyTyped-tools. I suspect it's not relevant to the developer case of DT-tools installed in a clone of DefinitelyTyped, and running on a single types/ folder. @bradzacher does that sound likely?

If that's the case, maybe dtslint could behave differently between a single run and a full run. Or it could be possible to make those rules part of a plugin as @remcohaszing suggested--I don't know eslint very well, so I've never worked with plugins.

**Comment by jakebailey** [comment]
A plugin is (roughly) just a CJS file which exports the lint rules; it just changes the mechanism by which the rules are loaded. We'd also set the default eslint config in the plugin and set a preset on DT to extend.

If all dt-tools is doing is calling the eslint API to lint things, then this method should work "just fine", because eslint would still find the same rules. It's just getting them from a different place.

**Comment by remcohaszing** [comment]
To make it an ESLint rule, the rules would need to be moved in a new package, e.g. `@definitelytyped/eslint-plugin`. This should be added as a `peerDependency` for `dtslint`. Then the rules in the config can be referenced via `@definitelytyped/dt-header`, `@definitelytypes/export-just-namespace`, etc. Then `rulePaths` can be removed from the `ESLint` constructor call.

**Comment by bradzacher** [comment]
> However, this may only apply to full, overnight runs, which download a copy of DefinitelyTyped alongside a clone of DefinitelyTyped-tools. I suspect it's not relevant to the developer case of DT-tools installed in a clone of DefinitelyTyped, and running on a single types/ folder.

That sounds about right. I'd you make the rules an npm package then the only version of TS-ESLint installed would be the one in the DT repo - so then you wouldn't have that problem of getting different instances of it accidentally.

**Comment by JoshuaKGoldberg** [comment]
FWIW I've been meaning to file an issue asking about this for a while. Most of the rest of the ecosystem works as plugins, and it's been a little inconvenient working on ESLint rules within DefinitelyTyped-tools with this extra oddity.

A few links for visibility:

* https://typescript-eslint.io/developers/custom-rules: general docs for individual custom rules _(DT's lint rules already pretty much follow it)_
* https://github.com/typescript-eslint/typescript-eslint/issues/5444: tracking task to document what should be done in this scenario

**Comment by remcohaszing** [comment]
An alternative solution would be to use the new ESLint flat config. Then it doesn’t matter where rules come from. I don’t know the current state of it though, whether it’s recommended to use already or not.

**Comment by bradzacher** [comment]
It's available for public use but it's still very much in the alpha stages.
