### ISSUE TITLE
Allow imports of deps listed both in devDependencies and in dependencies

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/DefinitelyTyped-tools#772]
I was trying to lock down the version of `marked` for testing `marked-terminal` by specifying a specific version in `devDependencies` while `dependencies` had a large range:

```
    "dependencies": {
        "@types/cardinal": "^2.1",
        "@types/node": "*",
        "chalk": "^5.3.0",
        "marked": ">=6.0.0 <10"
    },
    "devDependencies": {
        "@types/marked-terminal": "workspace:.",
        "marked": "6.0.0"
    },
```

but @definitelytyped/no-import-of-dev-dependencies complains about imports of `marked` after this.

**Comment by jakebailey** [comment]
Is this legal? Like, does a package manager understand this?

**Comment by andrewbranch** [comment]
pnpm does!
